version: "3"
services:
    nb:
        image: registry.cn-shanghai.aliyuncs.com/hellodock/jupyter_notebook:latest
#        image: "nb"
#        build: .
        working_dir: /home/jovyan/work
        volumes:
            - ./code:/home/jovyan/work
        ports:
            - 8888:8888
