version: '3'
services:
    db:
        image: mysql:5
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ../mysql/data:/var/lib/mysql
            - ../mysql/conf:/etc/mysql/conf.d
            - ../mysql/initdb:/docker-entrypoint-initdb.d
        expose:
            - 3306
        environment:
            MYSQL_DATABASE: did
            MYSQL_ROOT_PASSWORD: root

    cache:
        image: redis:4
        command: redis-server --appendonly yes
        restart: always
        volumes:
            - ../redis/data:/data
        expose:
            - 6379

    mq:
        image: rabbitmq:3
        hostname: rabbit
        restart: always
        expose:
            - 5672
        environment:
            RABBITMQ_ERLANG_COOKIE: rabbit_cookie

    task:
        image: django_in_docker
        build: .
        command: ./celery.sh
        restart: always
        working_dir: /root/code
        volumes:
            - ./:/root/code
        depends_on:
            - db
            - cache
            - mq

    task_viewer:
        image: django_in_docker
        build: .
        command: ./celery_flower.sh
        restart: always
        working_dir: /root/code
        volumes:
            - ./:/root/code
        ports:
            - 5555:5555
        depends_on:
            - task

    web:
        image: django_in_docker
        build: .
        command: ./launch.sh
        restart: always
        working_dir: /root/code
        volumes:
            - ./:/root/code
        ports:
            - 8000:8000
        depends_on:
            - db
            - cache
            - mq
