version: '3'
services:
    ftp:
        image: fauria/vsftpd:latest
        restart: always
        privileged: true
        ports:
            - "20:20"
            - "21:21"
            - "21100-21110:21100-21110"
        volumes:
            - ./files:/home/vsftpd
        environment:
            - FTP_USER=test
            - FTP_PASS=test
            - PASV_ADDRESS=127.0.0.1
            - PASV_MIN_PORT=21100
            - PASV_MAX_PORT=21110
