version: "3"
services:
    web:
        image: "java-app"
        command: "java Hello"
        build: .
        restart: always
        working_dir: /usr/code/
        volumes:
            - ./:/usr/code/
